# Generated by Django 2.2.3 on 2019-07-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='owoner',
            new_name='owner',
        ),
    ]
